version: "3"
services:
  backend:
    image: troias/strapi-next-base:backend
    container_name: projectOne-backend
    volumes:
      - ./backend:/srv/app
    ports:
      - "1337:1337"


#   frontend:
#     image:  frontend
#     container_name: frontend
#     volumes:
#       - ./frontend:/usr/src/app
#     environment:
#       - API_BASEURL=https://localhost:1337
#     ports:
#       - 3000:3000
#     depends_on: 
#       - backend
#     restart: on-failure
#     command: yarn dev
